name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: yarn install

      - name: Build packages
        run: yarn build

      - name: Static testing
        run: yarn validate

        env:
          CI: true
