name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_static_testing:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: yarn install

      - name: Build packages
        run: yarn build

      - name: Static testing
        run: yarn validate

        env:
          CI: true

  release:
    runs-on: ubuntu-latest

    needs: build_and_static_testing

    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Prepare publish
        run: |
          git config user.email "${{ github.event.head_commit.author.email }}"
          git config user.name "${{ github.event.head_commit.author.name }}"
          git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
          git checkout master

      - name: Release to NPM
        run: npx lerna publish -y

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          CI: true
